<?php

$labels = array();
$labels['key_management'] = 'OpenPGP key management';
$labels['generate_keys'] = 'Generate keys';
$labels['private_keys'] = 'Private keys';
$labels['public_keys'] = 'Public keys';
$labels['passphrase'] = 'Passphrase';
$labels['verify'] = 'Verify';
$labels['bits'] = 'Bits';
$labels['generate'] = 'Generate';
$labels['import'] = 'Import';
$labels['import_private'] = 'Import private key';
$labels['import_public'] = 'Import public key';
$labels['fingerprint'] = 'Fingerprint';
$labels['person'] = 'Person';
$labels['status'] = 'Status';
$labels['action'] = 'Action';

?>
